/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'e3stadnicar' at '6/4/16 8:42 PM' with Gradle 2.13
 *
 * @author e3stadnicar, @date 6/4/16 8:42 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
